name: fast_flutter_template
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  auto_route: ^7.8.4
  awesome_flutter_extensions: ^1.1.1
  cached_network_image: ^3.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  logger: ^2.0.2+1
  package_info_plus: ^4.2.0
  rate_my_app: ^2.0.0
  riverpod_annotation: ^2.2.1
  settings_ui: ^2.0.2
  url_launcher: ^6.2.0

dev_dependencies:
  custom_lint: ^0.5.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.3.3
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true
